apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: gen-role
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/NautiluX/gen-role/releases/download/v0.1.0/gen-role_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./gen-role"
      to: "."
    - from: LICENSE
      to: "."
    bin: "gen-role"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/NautiluX/gen-role/releases/download/v0.1.0/gen-role_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./gen-role"
      to: "."
    - from: LICENSE
      to: "."
    bin: "gen-role"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/NautiluX/gen-role/releases/download/v0.1.0/gen-role_windows_amd64.zip
    sha256: ""
    files:
    - from: "/gen-role.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "gen-role.exe"
  shortDescription: A new plugin
  homepage: https://github.com/NautiluX/gen-role
  caveats: |
    Usage:
      $ kubectl gen-role

    For additional options:
      $ kubectl gen-role --help
      or https://github.com/NautiluX/gen-role/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
